# Generated by Django 3.1.2 on 2020-10-22 09:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dist', models.CharField(max_length=50)),
                ('first_gapa', models.CharField(max_length=50)),
                ('first_type', models.CharField(max_length=50)),
                ('sum_area', models.FloatField()),
                ('sum_househ', models.FloatField()),
                ('sum_total', models.FloatField()),
                ('sum_male', models.FloatField()),
                ('sum_female', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
